# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  # powerManagement.enable = true;
  # powerManagement.cpuFreqGovernor = "schedutil";

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [
    # "processor.max_cstate=1"
    "initcall_blacklist=acpi_cpufreq_init"
    "amd_pstate=passive"
    "amd_prefcore=enable"
  ];
  hardware.cpu.amd.updateMicrocode = true;

  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # services.osquery.enable = true;
  # services.xserver.videoDrivers = [ "nvidia" ];
  # hardware.nvidia.open = true
  boot.loader.systemd-boot.memtest86.enable = true;
  # hardware.nvidia = {
  #   modesetting.enable = true;
  #   powerManagement.enable = true;
  # };
  
  # fick mich
  # nixpkgs.config.allowUnfree = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/538df4f3-5d7a-4b3a-86e8-48324c0106aa";
      fsType = "ext4";
    };

  swapDevices = [ ];

}
