# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{

  home-manager.users.cab = {
    imports = [ ./home.nix ];
  };

  users.users.cab.passwordFile = "/secrets/password";
  users.users.root.passwordFile = "/secrets/password";

  nix.settings.trusted-public-keys = [ "keter-builders:tkX3vAac9+Zg9v0hGcCfuPBkykQm/PNQ4/QNpz4Ulgc=" ];

  # dns = [ "1.1.1.1" "1.0.0.1" "2606:4700:4700::1111" "2606:4700:4700::1001" ];
  networking.wg-quick.interfaces."keter".configFile = "/secrets/keter.conf";

  # From 'not-detected.nix'
  hardware.enableRedistributableFirmware = lib.mkDefault true;

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "nvme" "dm-snapshot" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];

  boot.loader.timeout = 0;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.gpgSupport = true;
  boot.initrd.luks.devices = {
    rootfs = {
      gpgCard = {
        gracePeriod = 1; # needs some time to connect
        encryptedPass = ./luks.asc;
        publicKey = ./pubkey.asc;
      };
      device = "/dev/disk/by-label/yuna-root";
      preLVM = true;
      allowDiscards = true;
    };
  };

  fileSystems."/" =
    {
      device = "/dev/0/yuna-root";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-label/yuna-boot";
      fsType = "vfat";
    };

  swapDevices = [
    { device = "/var/swapfile"; size = 2 * 1024; }
  ];

}
